"""Rebrand transition (0.9.2 / METH-FU-TAUTLINE-FALLBACK-REMOVAL groundwork): the config surface
moves to ~/.config/tautline/tautline.env with the legacy ~/.config/minervit/methodology.env kept as
a byte-identical compatibility mirror, TAUTLINE_* env aliases are emitted everywhere MINERVIT_* is,
and install-cli preserves an operator pin set that already trusts the install HEAD.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _home_paths(home: Path) -> tuple[Path, Path]:
    new = home / ".config" / "tautline" / "tautline.env"
    legacy = home / ".config" / "minervit" / "methodology.env"
    return new, legacy


# --- resolve_user_config_env -----------------------------------------------------------------


def test_resolve_user_config_env_prefers_new_then_legacy_then_new_default(cli, tmp_path, monkeypatch):
    new = tmp_path / "tautline.env"
    legacy = tmp_path / "methodology.env"
    monkeypatch.setattr(cli, "USER_CONFIG_ENV", new)
    monkeypatch.setattr(cli, "LEGACY_USER_CONFIG_ENV", legacy)

    assert cli.resolve_user_config_env() == new  # neither exists -> new default

    legacy.write_text("export X=1\n", encoding="utf-8")
    assert cli.resolve_user_config_env() == legacy  # legacy fallback

    new.write_text("export X=1\n", encoding="utf-8")
    assert cli.resolve_user_config_env() == new  # new wins when both exist


# --- brand_env_pairs ---------------------------------------------------------------------------


# --- install-cli: new file + legacy mirror + aliases + migration ------------------------------


def test_install_cli_writes_tautline_env_and_legacy_mirror(run_cli, tmp_path):
    home = tmp_path / "home"
    res = run_cli("install-cli")
    assert res.returncode == 0, res.stderr
    new, legacy = _home_paths(home)
    assert new.is_file() and legacy.is_file()
    new_text = new.read_text(encoding="utf-8")
    assert new_text == legacy.read_text(encoding="utf-8"), "legacy mirror must stay byte-identical"
    assert "export TAUTLINE_METHODOLOGY_REPO=" in new_text
    assert "export MINERVIT_METHODOLOGY_REPO=" in new_text
    assert (new.stat().st_mode & 0o077) == 0
    assert (legacy.stat().st_mode & 0o077) == 0


def test_install_cli_migrates_preserved_exports_from_legacy_env(run_cli, tmp_path):
    home = tmp_path / "home"
    _, legacy = _home_paths(home)
    legacy.parent.mkdir(parents=True)
    legacy.write_text(
        "# Generated by tautline install-cli.\n"
        "export MINERVIT_METHODOLOGY_REPO=/old\n"
        "export MY_WEBHOOK_URL=https://example.invalid/hook\n",
        encoding="utf-8",
    )
    res = run_cli("install-cli")
    assert res.returncode == 0, res.stderr
    new, _ = _home_paths(home)
    assert "export MY_WEBHOOK_URL=https://example.invalid/hook" in new.read_text(encoding="utf-8")


def test_install_cli_merges_preserved_exports_by_name_preferred_file_wins(run_cli, tmp_path):
    # Codex 0.9.2 R1 P2: with different values for the SAME variable in both surfaces, the
    # preferred (tautline) value must win; exact-line dedup would source the stale legacy value last.
    home = tmp_path / "home"
    new, legacy = _home_paths(home)
    new.parent.mkdir(parents=True)
    legacy.parent.mkdir(parents=True)
    new.write_text("export MY_WEBHOOK_URL=https://example.invalid/current\n", encoding="utf-8")
    legacy.write_text("export MY_WEBHOOK_URL=https://example.invalid/stale\n", encoding="utf-8")
    res = run_cli("install-cli")
    assert res.returncode == 0, res.stderr
    text = new.read_text(encoding="utf-8")
    assert "export MY_WEBHOOK_URL=https://example.invalid/current" in text
    assert "https://example.invalid/stale" not in text, "stale legacy value must not shadow the preferred one"


def test_uninstall_cli_default_removes_both_config_surfaces(run_cli, tmp_path):
    # Codex 0.9.2 R1 P2: a default install writes both surfaces (the legacy mirror can hold
    # preserved secrets); a default uninstall must remove both unless --keep-env.
    home = tmp_path / "home"
    install = run_cli("install-cli")
    assert install.returncode == 0, install.stderr
    new, legacy = _home_paths(home)
    assert new.is_file() and legacy.is_file()
    res = run_cli("uninstall-cli")
    assert res.returncode == 0, res.stderr
    assert not new.exists(), "preferred config must be removed"
    assert not legacy.exists(), "legacy mirror (may hold secrets) must be removed"


def test_uninstall_cli_keep_env_keeps_both_config_surfaces(run_cli, tmp_path):
    home = tmp_path / "home"
    install = run_cli("install-cli")
    assert install.returncode == 0, install.stderr
    res = run_cli("uninstall-cli", "--keep-env")
    assert res.returncode == 0, res.stderr
    new, legacy = _home_paths(home)
    assert new.is_file() and legacy.is_file()


# --- emitted shim / launcher / hook honor both surfaces ---------------------------------------


def test_installed_shim_sources_tautline_env_first_and_exports_both(run_cli, tmp_path):
    home = tmp_path / "home"
    res = run_cli("install-cli")
    assert res.returncode == 0, res.stderr
    shim_text = (home / ".local" / "bin" / "tautline").read_text(encoding="utf-8")
    assert ".config/tautline/tautline.env" in shim_text
    assert ".config/minervit/methodology.env" in shim_text  # legacy fallback retained
    assert shim_text.index("tautline/tautline.env") < shim_text.index("minervit/methodology.env")
    assert 'TAUTLINE_METHODOLOGY_REPO_PRESET' in shim_text or "${TAUTLINE_METHODOLOGY_REPO:-" in shim_text
    assert "export TAUTLINE_METHODOLOGY_REPO" in shim_text


def test_installed_shim_prefers_tautline_repo_after_sourcing(run_cli, tmp_path):
    home = tmp_path / "home"
    res = run_cli("install-cli")
    assert res.returncode == 0, res.stderr
    shim_text = (home / ".local" / "bin" / "tautline").read_text(encoding="utf-8")
    # The post-source read on the preferred-config branch must consult TAUTLINE_* first.
    idx = shim_text.index('. "$CONFIG_ENV"')
    tail = shim_text[idx:]
    assert 'MINERVIT_METHODOLOGY_REPO_ENV="${TAUTLINE_METHODOLOGY_REPO:-${MINERVIT_METHODOLOGY_REPO:-}}"' in tail


def test_install_cli_dry_run_discloses_legacy_mirror(run_cli):
    res = run_cli("install-cli", "--dry-run")
    assert res.returncode == 0, res.stderr
    assert "legacy compatibility mirror" in res.stdout
    assert ".config/minervit/methodology.env" in res.stdout
