"""RCA 2026-07-22 controls 2 and 4: a lost maintainer-mode standdown, and generated launchers
that no longer match the generator.

Both controls exist because of one incident. An operator whose exec-root deliberately tracks a
non-release branch had maintainer mode armed -- the supported machine-wide update-gate standdown.
A later session hand-rewrote the config env file for an unrelated reason, the mode key did not
survive that rewrite, and NOTHING reported the loss. The next launch through a different entry
point hit the non-release-branch refusal again, two days after the failure was declared closed.

Control 2 (this file's first half): arming leaves a marker in the state dir. `maintainer-mode off`
removes it -- that is an authorized disarm. A marker with no key anywhere is an UNAUTHORIZED
disarm: something edited the config env behind the mode's back, and every launch surface says so
until the operator either re-arms or accepts the disarm through the verb.

Control 4 (second half): a launcher this machine recorded as generated must still be the
generator's output. Two independent detections, because the record predates digests: content that
no longer carries the generated marker is a hand-replacement (detectable with no digest at all --
this is the July-20 class), and a recorded digest that no longer matches is an in-place edit.
"""
import json
from pathlib import Path

import pytest

from test_maintainer_mode import (
    _cli_module_for_home,
    _config_env_path,
    _maintainer_home,
    _sync_env,
    _verb,
)
from test_sync_methodology_cli import _make_methodology_fixture, _run_cli


@pytest.fixture()
def cli(monkeypatch, tmp_path):
    """A fresh CLI module per test with a hermetic HOME (see test_maintainer_mode)."""
    return _cli_module_for_home(monkeypatch, tmp_path / "home")


def _arm_key(cli) -> Path:
    config = cli.USER_CONFIG_ENV
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text("export TAUTLINE_METHODOLOGY_MAINTAINER_MODE=1\n", encoding="utf-8")
    return config


def _generated_launcher(path: Path, body: str = "exec claude\n") -> Path:
    """A file shaped like the generator's output: the generated marker plus a body."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"#!/bin/sh\n# {_GENERATED}\n{body}", encoding="utf-8")
    path.chmod(0o755)
    return path


_GENERATED = "Generated by tautline install-claude-launcher."


# --- Control 2: a lost standdown -----------------------------------------------------------


def test_never_armed_machine_never_reports_a_loss(cli):
    """No marker, no key: a stock machine must stay silent. The notice keys on the MARKER, not
    on the absence of the key, or every machine on earth would nag."""
    assert cli.read_maintainer_mode_arm_marker() is None
    assert cli.maintainer_mode_standdown_lost() is False
    assert cli.maintainer_mode_standdown_loss_lines() == []


def test_arm_marker_roundtrips_and_clears(cli):
    config = _arm_key(cli)
    written = cli.write_maintainer_mode_arm_marker(config)
    assert written == cli.maintainer_mode_arm_marker_path()

    marker = cli.read_maintainer_mode_arm_marker()
    assert marker is not None
    assert marker["schema"] == cli.MAINTAINER_MODE_ARM_MARKER_SCHEMA
    assert marker["configEnv"] == str(config)
    assert marker["armedAt"]

    assert cli.clear_maintainer_mode_arm_marker() is True
    assert cli.read_maintainer_mode_arm_marker() is None
    # Idempotent: clearing an already-clear machine is not an error.
    assert cli.clear_maintainer_mode_arm_marker() is False


def test_backfill_arms_the_witness_on_an_already_armed_machine(cli):
    """Without the backfill this control protects nobody who already needs it: a machine armed
    before the control shipped carries no marker, so a later silent disarm reports nothing --
    on exactly the machines the RCA is about."""
    config = _arm_key(cli)
    assert cli.read_maintainer_mode_arm_marker() is None

    cli.ensure_maintainer_mode_arm_marker()
    marker = cli.read_maintainer_mode_arm_marker()
    assert marker is not None
    assert marker["source"] == "observed", "a backfill must not claim to be a real arming"
    assert marker["configEnv"] == str(config)

    # Idempotent, and it never fabricates a marker on an unarmed machine.
    cli.ensure_maintainer_mode_arm_marker()
    assert cli.read_maintainer_mode_arm_marker()["armedAt"] == marker["armedAt"]
    config.unlink()
    cli.clear_maintainer_mode_arm_marker()
    cli.ensure_maintainer_mode_arm_marker()
    assert cli.read_maintainer_mode_arm_marker() is None


def test_backfill_refuses_when_the_mode_is_configured_but_not_armed(cli, monkeypatch, tmp_path):
    """Codex R2 P2. `configured but not armed` means the key is set with no checkout to manage:
    every gate runs stock and no standdown exists. A marker there would be a witness to nothing,
    and a later config cleanup would report the loss of a standdown that never stood down --
    a permanent false alarm on a machine that was never protected."""
    _arm_key(cli)
    # No checkout to manage -> configured, but not armed.
    monkeypatch.setattr(cli, "canonical_methodology_repo", lambda: tmp_path / "no-checkout")
    assert cli.maintainer_mode_configured() is True
    assert cli.maintainer_mode_armed() is False

    cli.ensure_maintainer_mode_arm_marker()
    assert cli.read_maintainer_mode_arm_marker() is None, (
        "an inert configured-but-not-armed machine must not get a witness"
    )


def test_backfilled_marker_still_detects_the_loss_and_says_it_was_observed(cli):
    config = _arm_key(cli)
    cli.ensure_maintainer_mode_arm_marker()
    config.unlink()
    assert cli.maintainer_mode_standdown_lost() is True
    greppable = [
        line
        for line in cli.maintainer_mode_standdown_loss_lines()
        if line.startswith("maintainer_mode_standdown_lost: ")
    ]
    assert "observed armed" in greppable[0], greppable


def test_marker_plus_live_key_is_not_a_loss(cli):
    config = _arm_key(cli)
    cli.write_maintainer_mode_arm_marker(config)
    assert cli.maintainer_mode_configured() is True
    assert cli.maintainer_mode_standdown_lost() is False
    assert cli.maintainer_mode_standdown_loss_lines() == []


def test_key_vanishing_from_every_surface_is_a_loss(cli):
    """THE incident, reduced: armed, then the config env is rewritten without the key."""
    config = _arm_key(cli)
    cli.write_maintainer_mode_arm_marker(config)

    # A hand-rewrite of the config env that drops the key -- exactly what happened on 2026-07-20.
    config.write_text("export TAUTLINE_METHODOLOGY_REPO=/somewhere\n", encoding="utf-8")

    assert cli.maintainer_mode_configured() is False
    assert cli.maintainer_mode_standdown_lost() is True


def test_loss_notice_names_both_remedies_and_stays_greppable(cli):
    config = _arm_key(cli)
    cli.write_maintainer_mode_arm_marker(config)
    config.unlink()

    lines = cli.maintainer_mode_standdown_loss_lines()
    assert lines, "a lost standdown must produce a notice"
    body = "\n".join(lines)
    # Re-arm, and the authorized way to accept the disarm and silence the notice.
    assert f"{cli.CLI_NAME} maintainer-mode on" in body
    assert f"{cli.CLI_NAME} maintainer-mode off" in body
    # One unprefixed machine-readable line, like every other `key: value` report line.
    greppable = [line for line in lines if line.startswith("maintainer_mode_standdown_lost: ")]
    assert len(greppable) == 1, lines
    assert str(config) in greppable[0]


def test_config_surface_deleted_entirely_is_still_a_loss(cli):
    """Deleting the file is the same unauthorized disarm as editing the key out of it."""
    config = _arm_key(cli)
    cli.write_maintainer_mode_arm_marker(config)
    config.unlink()
    assert cli.maintainer_mode_standdown_lost() is True


def test_unreadable_marker_never_reports_a_loss(cli):
    """Corrupt state is not evidence of a disarm. Fail silent, never nag on garbage."""
    path = cli.maintainer_mode_arm_marker_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{not json", encoding="utf-8")
    assert cli.read_maintainer_mode_arm_marker() is None
    assert cli.maintainer_mode_standdown_lost() is False


def test_status_line_reports_the_loss(cli):
    config = _arm_key(cli)
    cli.write_maintainer_mode_arm_marker(config)
    config.unlink()
    assert cli.maintainer_mode_status_line() == "maintainer_mode: off"
    assert cli.maintainer_mode_standdown_lost() is True


# --- Control 2: verb wiring (subprocess, real CLI) -------------------------------------------


def _marker_path(home: Path) -> Path:
    return home / ".local" / "state" / "minervit" / "maintainer-mode-armed.json"


def test_verb_on_writes_the_marker_and_off_clears_it(tmp_path):
    _source, clone, _lane = _make_methodology_fixture(tmp_path)
    home = _maintainer_home(tmp_path)

    on = _verb(clone, home, "on")
    assert on.returncode == 0, on.stdout + on.stderr
    marker = _marker_path(home)
    assert marker.is_file(), "arming must record that this machine was armed"
    assert json.loads(marker.read_text(encoding="utf-8"))["configEnv"] == str(
        _config_env_path(home)
    )

    off = _verb(clone, home, "off")
    assert off.returncode == 0, off.stdout + off.stderr
    assert not marker.exists(), "an authorized disarm must leave no loss notice behind"


def test_status_and_sync_report_an_unauthorized_disarm(tmp_path):
    """Arm, then strip the key the way a hand-rewrite would. Both the verb and the launch path
    must say so -- the launch path is the one that would have caught the incident."""
    _source, clone, _lane = _make_methodology_fixture(tmp_path)
    home = _maintainer_home(tmp_path)

    assert _verb(clone, home, "on").returncode == 0
    config = _config_env_path(home)
    config.write_text("export TAUTLINE_METHODOLOGY_REPO=/somewhere\n", encoding="utf-8")

    status = _verb(clone, home, "status")
    assert status.returncode == 0, status.stdout + status.stderr
    assert "maintainer_mode_standdown_lost:" in status.stdout + status.stderr

    sync = _run_cli(
        clone / "bin" / "tautline",
        "sync-methodology",
        "--no-remote",
        cwd=clone,
        env=_sync_env(home),
    )
    assert "maintainer_mode_standdown_lost:" in sync.stdout + sync.stderr, (
        sync.stdout + sync.stderr
    )


# --- Control 4: generated launchers that no longer match the generator -----------------------


def test_recording_stores_a_digest_and_still_reads_back_as_paths(cli):
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    assert cli.record_installed_launcher(launcher) is not None

    record = json.loads(cli.installed_launchers_path().read_text(encoding="utf-8"))
    assert record["schema"] == cli.INSTALLED_LAUNCHERS_SCHEMA
    assert record["launchers"][0]["path"] == str(launcher)
    assert record["launchers"][0]["sha256"]
    # The path-only reader is what every existing caller uses; its contract must not change.
    assert cli.read_installed_launchers() == [launcher]
    assert cli.diverged_installed_launchers() == []


def test_legacy_v1_record_reads_and_never_false_positives(cli):
    """Every launcher recorded before this control has no digest. A digest-less entry whose file
    is still the generator's output must read clean, or the upgrade nags the whole fleet."""
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    path = cli.installed_launchers_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"schema": "tautline-installed-launchers/v1", "launchers": [str(launcher)]}),
        encoding="utf-8",
    )
    assert cli.read_installed_launchers() == [launcher]
    assert cli.diverged_installed_launchers() == []


def test_hand_replaced_launcher_is_caught_without_any_digest(cli):
    """THE July-20 class: a generated launcher overwritten by a hand-written script. Caught from
    a digest-less v1 record, because the replacement does not carry the generated marker."""
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    path = cli.installed_launchers_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"schema": "tautline-installed-launchers/v1", "launchers": [str(launcher)]}),
        encoding="utf-8",
    )

    launcher.write_text(
        "#!/bin/sh\n# yolo -- operator launcher (custom).\nexec claude\n", encoding="utf-8"
    )

    assert cli.diverged_installed_launchers() == [
        (launcher, cli.LAUNCHER_DIVERGENCE_HAND_REPLACED)
    ]


def test_edited_generated_launcher_is_caught_by_the_digest(cli):
    """Still carries the generated marker, so only the digest can see it."""
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    cli.record_installed_launcher(launcher)

    launcher.write_text(
        f"#!/bin/sh\n# {_GENERATED}\n# operator tweak\nexec claude --yolo\n", encoding="utf-8"
    )

    assert cli.diverged_installed_launchers() == [(launcher, cli.LAUNCHER_DIVERGENCE_EDITED)]


def test_untouched_launcher_stays_clean(cli):
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    cli.record_installed_launcher(launcher)
    assert cli.diverged_installed_launchers() == []


def test_removed_launcher_is_not_reported(cli):
    """A launcher the operator deleted is not a divergence -- nagging about it forever would
    train the operator to ignore the notice that matters."""
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    cli.record_installed_launcher(launcher)
    launcher.unlink()
    assert cli.diverged_installed_launchers() == []


def test_launcher_replaced_by_a_binary_is_reported_without_hashing_it(cli):
    """A recorded path that has become a binary (or anything over the scan cap) is a replacement
    and must be reported -- but the size cap is what keeps every launch from reading it end to
    end, so the report cannot be allowed to depend on hashing it first."""
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    cli.record_installed_launcher(launcher)

    launcher.write_bytes(b"\x7fELF\x00\x00" + b"\x00" * 64)

    assert cli._launcher_digest(launcher) is not None  # small: still hashable
    assert cli._launcher_looks_generated(launcher) is False
    assert cli.diverged_installed_launchers() == [
        (launcher, cli.LAUNCHER_DIVERGENCE_HAND_REPLACED)
    ]

    # Over the scan cap: never hashed, still reported.
    launcher.write_bytes(b"#" * (cli.LAUNCHER_SCAN_MAX_BYTES + 1))
    assert cli._launcher_digest(launcher) is None
    assert cli.diverged_installed_launchers() == [
        (launcher, cli.LAUNCHER_DIVERGENCE_HAND_REPLACED)
    ]


def test_recording_preserves_other_launchers_digests(cli):
    first = _generated_launcher(cli.USER_BIN_DIR / "yolo")
    second = _generated_launcher(cli.USER_BIN_DIR / "yolo-verbose")
    cli.record_installed_launcher(first)
    cli.record_installed_launcher(second)

    assert sorted(cli.read_installed_launchers()) == sorted([first, second])
    first.write_text("#!/bin/sh\nhand written\n", encoding="utf-8")
    assert cli.diverged_installed_launchers() == [
        (first, cli.LAUNCHER_DIVERGENCE_HAND_REPLACED)
    ]


def test_divergence_notice_names_the_regeneration_command_per_launcher(cli):
    launcher = _generated_launcher(cli.USER_BIN_DIR / "yolo-verbose")
    lines = cli.launcher_divergence_lines([(launcher, cli.LAUNCHER_DIVERGENCE_HAND_REPLACED)])
    body = "\n".join(lines)
    assert f"install-claude-launcher --name {launcher.name} --force" in body
    greppable = [line for line in lines if line.startswith("launcher_divergence: ")]
    assert len(greppable) == 1, lines
    assert str(launcher) in greppable[0]
    assert cli.LAUNCHER_DIVERGENCE_HAND_REPLACED in greppable[0]


def test_regeneration_command_replays_the_options_the_launcher_was_installed_with(cli, tmp_path):
    """Codex R1 P2. The bare `--name <basename> --force` line is correct ONLY for a default
    install. For `--bin-dir` it regenerates the wrong file and leaves the divergence; for an
    OPERATOR launcher it would replace a deliberately non-blocking launcher with a gated one --
    the exact failure this RCA exists to end. So the options are recorded and replayed."""
    elsewhere = tmp_path / "other-bin"
    operator = elsewhere / "yolo"

    assert cli.launcher_regeneration_command(
        operator,
        {"binDir": str(elsewhere), "operatorChannel": "experimental", "runtime": "/r/t"},
    ) == (
        f"{cli.CLI_NAME} install-claude-launcher --name yolo --bin-dir {elsewhere} "
        "--operator-channel experimental --runtime /r/t --force"
    )

    # A default launcher installed with skip-permissions keeps that flag; the default bin dir is
    # omitted because repeating it adds nothing.
    assert cli.launcher_regeneration_command(
        cli.USER_BIN_DIR / "claude-x",
        {"binDir": str(cli.USER_BIN_DIR), "skipPermissions": True},
    ) == (
        f"{cli.CLI_NAME} install-claude-launcher --name claude-x "
        "--dangerously-skip-permissions --force"
    )

    # No recorded metadata (every record written before this release): the line must NOT pretend
    # to be exact. It names the default form and says the original options have to be re-added.
    hedged = cli.launcher_regeneration_command(cli.USER_BIN_DIR / "yolo", None)
    assert hedged.startswith(f"{cli.CLI_NAME} install-claude-launcher --name yolo --force")
    assert "--operator-channel" in hedged and "originally installed with" in hedged


def test_recorded_install_options_reach_the_divergence_notice(cli, tmp_path):
    elsewhere = tmp_path / "other-bin"
    launcher = _generated_launcher(elsewhere / "yolo")
    cli.record_installed_launcher(
        launcher, {"binDir": str(elsewhere), "operatorChannel": "experimental"}
    )
    launcher.write_text("#!/bin/sh\nhand written\n", encoding="utf-8")

    body = "\n".join(cli.launcher_divergence_lines(cli.diverged_installed_launchers()))
    assert f"--bin-dir {elsewhere}" in body
    assert "--operator-channel experimental" in body
    assert "originally installed with" not in body, "metadata was recorded; do not hedge"


def test_sync_reports_a_diverged_launcher(tmp_path):
    """The launch path is where this has to surface: the operator only ever sees a launch."""
    _source, clone, _lane = _make_methodology_fixture(tmp_path)
    home = _maintainer_home(tmp_path)
    launcher = _generated_launcher(home / ".local" / "bin" / "yolo")
    record = home / ".local" / "state" / "minervit" / "installed-launchers.json"
    record.parent.mkdir(parents=True, exist_ok=True)
    record.write_text(
        json.dumps(
            {"schema": "tautline-installed-launchers/v1", "launchers": [str(launcher)]}
        ),
        encoding="utf-8",
    )
    launcher.write_text("#!/bin/sh\n# custom\nexec claude\n", encoding="utf-8")

    sync = _run_cli(
        clone / "bin" / "tautline",
        "sync-methodology",
        "--no-remote",
        cwd=clone,
        env=_sync_env(home),
    )
    assert "launcher_divergence:" in sync.stdout + sync.stderr, sync.stdout + sync.stderr


# --- Control 1: the refusal must name its own control ------------------------------------------
#
# Control 1, not "2a". The RCA's control 1 is "name the correct control in the refusal"; control 2
# is "detect a lost standdown" (this file's first half). The behavioural pin for control 1 now
# lives in test_sync_methodology_cli.py, where the sync runtime fixture is, and asserts the
# EMITTED refusal -- ordering and framing -- rather than grepping cli.py's source. What remains
# here is the label assertion: the mislabel is why the intake kept reading control 1 as open.


def test_control_1_surfaces_are_labelled_control_1(cli):
    """The comment in cli.py used to credit this refusal to "control 2", and this section header
    used to read "Control 2a". Both described control 1's work, so every reader looking for
    control 1's implementation found nothing and every reader of control 2 found an extra thing.

    Behaviour is pinned by
    test_sync_methodology_cli.py::test_emitted_non_release_branch_refusal_names_maintainer_mode_before_the_bypass;
    this asserts only the labels, so a comment edit cannot fail a behavioural test and vice versa.
    """
    text = Path(cli.__file__).read_text(encoding="utf-8")
    refusal_block = text[text.index("refusing to sync from a non-release branch"):][:1200]
    assert "RCA 2026-07-22 control 1:" in refusal_block, (
        "the non-release-branch refusal must credit control 1, the control it implements:\n"
        + refusal_block
    )
    assert "control 2:" not in refusal_block, (
        "the old 'control 2' mislabel is back:\n" + refusal_block
    )

    # BOTH surfaces, not just cli.py's. Reading only `cli.__file__` would leave this file's own
    # header free to drift back to "Control 2a" with the test still green -- a test asserting less
    # than it claims, which is the exact defect this whole change exists to remove. Caught in
    # stage-2 review of the change that introduced it.
    # Anchored on the specific header, NOT on the first "# --- Control" in the file: this file's
    # first half is genuinely control 2 (a lost standdown), so an index-of-first match asserts
    # against the wrong section and fails for the wrong reason.
    #
    # The negative check scans SECTION HEADER LINES only, never the whole file. Scanning the whole
    # file makes this test fail on any prose that merely NAMES the old label -- including this
    # comment -- which is the same match-what-you-discuss defect the plan-precheck fixed in 0.27.0.
    own_source = Path(__file__).read_text(encoding="utf-8")
    assert "# --- Control 1: the refusal must name its own control" in own_source, (
        "this section pins control 1's label and must itself be labelled control 1"
    )
    headers = [line for line in own_source.splitlines() if line.startswith("# --- ")]
    stale = [line for line in headers if "Control 2a" in line]
    assert not stale, f"the old section mislabel is back in a header: {stale}"
